name: GitHub-Profile-3D-Contrib-fixed

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: gumbobrot/github-profile-3d-contrib@0.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.nishanmudalige }}
      - name: Pull latest changes
        run: git pull --force origin main
      - name: Commit & Push
        run: |
          git config nishanmudalige github-actions
          git config nishanmudalige@gmail.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push

